## ANALISE DO DADOS:

In [37]:
#Importar a biblioteca pandas
import pandas as pd

In [38]:
df = pd.read_csv('data/student-mat.csv', sep=';')

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   escola                         395 non-null    str
 1   sexo                           395 non-null    str
 2   idade                          395 non-null    int64
 3   endereco                       395 non-null    str
 4   tamanho_da_familia             395 non-null    str
 5   coabitacao_pais                395 non-null    str
 6   escolaridade_mae               395 non-null    int64
 7   escolaridade_pai               395 non-null    int64
 8   trabalho_mae                   395 non-null    str
 9   trabalho_pai                   395 non-null    str
 10  razao                          395 non-null    str
 11  guardia(o)                     395 non-null    str
 12  tempo_viagem_escola            395 non-null    int64
 13  hora_de_estudar                395 non-null    int64
 14  n_reprovacoes                  395 non-null    int64
 15  apoio_educacional_extra        395 non-null    str
 16  apoio_educacional_familiar     395 non-null    str
 17  aulas_extras_pagas             395 non-null    str
 18  atividades_extracurriculares   395 non-null    str
 19  bercario                       395 non-null    str
 20  deseja_ensino_superior         395 non-null    str
 21  internet                       395 non-null    str
 22  romantico                      395 non-null    str
 23  qualidade_relacoes_familiares  395 non-null    int64
 24  tempo_livre                    395 non-null    int64
 25  sair_com_amigos                395 non-null    int64
 26  Dalc                           395 non-null    int64
 27  Walc                           395 non-null    int64
 28  estado_saude_atual             395 non-null    int64
 29  n_faltas_escolares             395 non-null    int64
 30  nota1                          395 non-null    int64
 31  nota2                          395 non-null    int64
 32  nota3                          395 non-null    int64
dtypes: int64(16), str(17)
memory usage: 102.0 KB

## Observações:
- Dalc: Consumo de álcool durante a semana de trabalho
- Walc: Consumo de álcool nos fins de semana

In [40]:
df.shape

(395, 33)

In [41]:
df.tail()

,escola,sexo,idade,endereco,tamanho_da_familia,coabitacao_pais,escolaridade_mae,escolaridade_pai,trabalho_mae,trabalho_pai,...,qualidade_relacoes_familiares,tempo_livre,sair_com_amigos,Dalc,Walc,estado_saude_atual,n_faltas_escolares,nota1,nota2,nota3
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [42]:
df.dtypes

escola                             str
sexo                               str
idade                            int64
endereco                           str
tamanho_da_familia                 str
coabitacao_pais                    str
escolaridade_mae                 int64
escolaridade_pai                 int64
trabalho_mae                       str
trabalho_pai                       str
razao                              str
guardia(o)                         str
tempo_viagem_escola              int64
hora_de_estudar                  int64
n_reprovacoes                    int64
apoio_educacional_extra            str
apoio_educacional_familiar         str
aulas_extras_pagas                 str
atividades_extracurriculares       str
bercario                           str
deseja_ensino_superior             str
internet                           str
romantico                          str
qualidade_relacoes_familiares    int64
tempo_livre                      int64
sair_com_amigos                  int64
Dalc                             int64
Walc                             int64
estado_saude_atual               int64
n_faltas_escolares               int64
nota1                            int64
nota2                            int64
nota3                            int64
dtype: object

In [43]:
df['estado_saude_atual'].value_counts()

estado_saude_atual
5    146
3     91
4     66
1     47
2     45
Name: count, dtype: int64

## OBSERVAÇÕES:
- Os dados não possuem valores nulos;
- Será necessário tratar a sexo

## EXTRAÇÃO 1:

Nessa etapa busco extrair as possiveis variaveis que poderão ser uteis como dataset base dos meus modelos, partindo da seguinte pergunta:

- É realmente necessario utilizar está coluna como criterio de avaliação?

In [44]:
df_extrc1=df.drop(['escola','endereco','tamanho_da_familia','trabalho_mae','trabalho_pai','razao','guardia(o)','aulas_extras_pagas','bercario','deseja_ensino_superior','romantico','qualidade_relacoes_familiares','tempo_livre','sair_com_amigos','Dalc','Walc'],axis=1)

In [45]:
df_extrc1.tail()

,sexo,idade,coabitacao_pais,escolaridade_mae,escolaridade_pai,tempo_viagem_escola,hora_de_estudar,n_reprovacoes,apoio_educacional_extra,apoio_educacional_familiar,atividades_extracurriculares,internet,estado_saude_atual,n_faltas_escolares,nota1,nota2,nota3
390,M,20,A,2,2,1,2,2,no,yes,no,no,4,11,9,9,9
391,M,17,T,3,1,2,1,0,no,no,no,yes,2,3,14,16,16
392,M,21,T,1,1,1,1,3,no,no,no,no,3,3,10,8,7
393,M,18,T,3,2,3,1,0,no,no,no,yes,5,0,11,12,10
394,M,19,T,1,1,1,1,0,no,no,no,yes,5,5,8,9,9

In [46]:
df_extrc1.info()

<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   sexo                          395 non-null    str
 1   idade                         395 non-null    int64
 2   coabitacao_pais               395 non-null    str
 3   escolaridade_mae              395 non-null    int64
 4   escolaridade_pai              395 non-null    int64
 5   tempo_viagem_escola           395 non-null    int64
 6   hora_de_estudar               395 non-null    int64
 7   n_reprovacoes                 395 non-null    int64
 8   apoio_educacional_extra       395 non-null    str
 9   apoio_educacional_familiar    395 non-null    str
 10  atividades_extracurriculares  395 non-null    str
 11  internet                      395 non-null    str
 12  estado_saude_atual            395 non-null    int64
 13  n_faltas_escolares            395 non-null    int64
 14  nota1                         395 non-null    int64
 15  nota2                         395 non-null    int64
 16  nota3                         395 non-null    int64
dtypes: int64(11), str(6)
memory usage: 52.6 KB

## EXTRAÇÃO 2:

Nessa segunda etapa, busco refinar ainda mais as variaveis que irei utilizar e tambem pela existencia de variaveis strings, busco transforma las em valores numericos para os modelos conseguirem prever.

In [47]:
df_extrc2=df_extrc1.drop(['coabitacao_pais','escolaridade_mae','escolaridade_pai','apoio_educacional_extra','apoio_educacional_familiar','atividades_extracurriculares'],axis=1)

In [48]:
df_extrc2.info()

<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   sexo                 395 non-null    str
 1   idade                395 non-null    int64
 2   tempo_viagem_escola  395 non-null    int64
 3   hora_de_estudar      395 non-null    int64
 4   n_reprovacoes        395 non-null    int64
 5   internet             395 non-null    str
 6   estado_saude_atual   395 non-null    int64
 7   n_faltas_escolares   395 non-null    int64
 8   nota1                395 non-null    int64
 9   nota2                395 non-null    int64
 10  nota3                395 non-null    int64
dtypes: int64(9), str(2)
memory usage: 34.1 KB

In [49]:
df_extrc2['sexo'].value_counts()

sexo
F    208
M    187
Name: count, dtype: int64

In [50]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df_extrc2["genero"] = encoder.fit_transform(df_extrc2["sexo"])
df_extrc2=df_extrc2.drop(['sexo'],axis=1)

df_extrc2['reprovacao']=(df['n_reprovacoes'] > 0).astype(int)
df_extrc2=df_extrc2.drop(['n_reprovacoes'],axis=1)

In [51]:
df_extrc2['internet']=encoder.fit_transform(df_extrc2['internet'])

In [52]:
df_extrc2.tail()

,idade,tempo_viagem_escola,hora_de_estudar,internet,estado_saude_atual,n_faltas_escolares,nota1,nota2,nota3,genero,reprovacao
390,20,1,2,0,4,11,9,9,9,1,1
391,17,2,1,1,2,3,14,16,16,1,0
392,21,1,1,0,3,3,10,8,7,1,1
393,18,3,1,1,5,0,11,12,10,1,0
394,19,1,1,1,5,5,8,9,9,1,0

In [53]:
df_extrc2.to_csv('arquivo_tratado.csv',index=False,sep=',')

In [54]:
df_extrc2

,idade,tempo_viagem_escola,hora_de_estudar,internet,estado_saude_atual,n_faltas_escolares,nota1,nota2,nota3,genero,reprovacao
0,18,2,2,0,3,6,5,6,6,0,0
1,17,1,2,1,3,4,5,5,6,0,0
2,15,1,2,1,3,10,7,8,10,0,1
3,15,1,3,1,5,2,15,14,15,0,0
4,16,1,2,0,5,4,6,10,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...
390,20,1,2,0,4,11,9,9,9,1,1
391,17,2,1,1,2,3,14,16,16,1,0
392,21,1,1,0,3,3,10,8,7,1,1
393,18,3,1,1,5,0,11,12,10,1,0
394,19,1,1,1,5,5,8,9,9,1,0